### ISSUE TITLE
New Event Submission : talk "Je fais du Python2 en 2024" en Septembre 2024

### ISSUE THREAD

**Issue by Lenormju** [meetup-python-grenoble/meetup-python-grenoble.github.io#188]
### Title

Je fais du Python2 en 2024

### Pitch

Et c'est infernal ! Mais pourquoi s'infliger cette douleur ? Et au fait, qu'est-ce que ça change ?

Je voudrais vous partager ma frustration de devoir encore maintenir du code dans une version dépréciée du langage (c'est-à-dire vous vanter toutes les bonnes choses de Python3 !). Et ce sera l'occasion de faire un petit retour sur les origines du Python que nous aimons tant, son héritage qui perdure encore aujourd'hui (pour le meilleur et parfois pour le pire !).

### Theme

Other

### Kind

Talk

### Duration

30mn

### Speaker Name

Julien Lenormand

### Speaker Bio

https://sessionize.com/lenormand-julien/

### Sponsored

No

### Availability

- [ ] January
- [ ] February
- [ ] March
- [ ] April
- [ ] May
- [ ] June
- [ ] July
- [ ] August
- [X] September
- [ ] October
- [ ] November
- [ ] December

**Comment by Pierre-Loic** [comment]
ok, c'est validé pour le 19 septembre : https://www.meetup.com/fr-FR/groupe-dutilisateurs-python-grenoble/events/303176695/
