### ISSUE TITLE
New Event Submission : several topics

### ISSUE THREAD

**Issue by Lenormju** [meetup-python-grenoble/meetup-python-grenoble.github.io#191]
### Title

Either "Rust, meilleur ami de Python", or "les Monades en Python", or #48

### Pitch

TODO

### Theme

Other

### Kind

Talk

### Duration

15mn

### Speaker Name

Julien Lenormand

### Speaker Bio

Serial Talker pour Kaizen Solutions

### Sponsored

No

### Availability

- [ ] January
- [ ] February
- [ ] March
- [ ] April
- [ ] May
- [ ] June
- [ ] July
- [ ] August
- [ ] September
- [ ] October
- [ ] November
- [X] December

**Comment by Pierre-Loic** [comment]
Ok pour le lightning talk **"Rust, meilleur ami de Python"** pour le 17 décembre
