### ISSUE TITLE
Event: A la quête de l'objet factice !

### ISSUE THREAD

**Issue by sbauza** [meetup-python-grenoble/meetup-python-grenoble.github.io#21]
### Title

A la quête de l'objet factice !

### Pitch

L'adage dit "Tester c'est douter !"
Vous avez déjà écrit du code Python, c'est bien. Mais écrire des tests, c'est mieux ;)
Seulement voila, pour écrire de bons tests, il faut partir en quête d'un objet étrange, le bouchon ! Et si on en profitait pour regarder ce qu'il est possible de faire en Python ?
Lançons nous dans l'aventure armés de notre épée (nos doigts) et de notre bouclier (notre éditeur favori) dans les contrées des deux frameworks de tests principaux en Python.
Attention, des (mots-clés) barbares comme pytest, unittest, mock, fixture et autres tox pourraient être rencontrés durant ce meetup qu'ils nous faudra combattre :-)

### Theme

Other

### Kind

Talk

### Duration

60mn

### Sponsored

No

### Availability

- [ ] January
- [ ] February
- [ ] March
- [ ] April
- [ ] May
- [ ] June
- [ ] July
- [ ] August
- [ ] September
- [ ] October
- [X] November
- [X] December

**Comment by sbauza** [comment]
Ajout de René Ribaud @Uggla comme co-présentateur

**Comment by rclement** [comment]
@sbauza @uggla Merci pour votre contribution !

L'événement est en ligne sur le siteweb, l'annonce sera effectuée demain sur LinkedIn et Meetup : https://meetup-python-grenoble.github.io/events/2022-11-24/

**Comment by rclement** [comment]
Ressources ajoutées par @sbauza dans la PR #24 . Merci à tous les 2 pour ce meetup ! 🙏
