### ISSUE TITLE
Atelier du Tech for Good Tour

### ISSUE THREAD

**Issue by ElisePupier** [meetup-python-grenoble/meetup-python-grenoble.github.io#44]
### Title

Tech for Good Tour

### Pitch

Le Tech for Good Tour est un atelier de deux heures avec au cœur...
🌎 des méthodes participatives permettant à chacun·e de s’approprier les enjeux sociaux et environnementaux liés au numérique,
⚡️ des méthodologies d’intelligence collective permettant aux participant·es de faire un premier pas dans l’engagement pour construire une tech plus engagée et responsable.
Il est proposé partout en France au printemps, en particulier aux étudiant·e·s et professionel·le·s du secteur du numérique.

### Theme

Other

### Kind

Workshop

### Duration

60mn

### Sponsored

No

### Availability

- [ ] January
- [X] February
- [X] March
- [X] April
- [X] May
- [X] June
- [ ] July
- [ ] August
- [ ] September
- [ ] October
- [ ] November
- [ ] December

**Comment by Pierre-Loic** [comment]
@ElisePupier Je te propose la mise à jour suivante pour le pitch du meetup de février : dis-moi ce que tu en penses

**Title**

Python for Good

**Pitch**

Avec le langage Python, on peut (presque) tout faire : automatiser des tâches, créer des plateforme web, analyser des données, entrainer des algorithmes d'intelligence artificielle et tant d'autres choses. Mais, pour citer Isaac Asimov, "un grand pouvoir donne de grandes responsabilités". Donc pourquoi ne pas utiliser le pouvoir de Python pour améliorer le monde ? Pour le Meetup Python de Février, nous vous proposons un atelier avec l'association Data for Good pour collaborer sur des données ouvertes.
Que vous soyez novice ou expérimenté dans la valorisation des données en Python, venez participer à ce Meetup collaboratif et engagé !
N'oubliez pas de ramener votre ordinateur !

**Comment by rclement** [comment]
L'événement est prévu pour le 28 février 2023 et est en ligne :
https://meetup-python-grenoble.github.io/events/2023-02-28/
